// <auto-generated />
using System; 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.AspNetCore.NewDb.Migrations
{
//    [DbContext(typeof(BloggingContext))]
//    [Migration("20180905105453_InitialCreate")]
//    partial class InitialCreate
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Care", b =>
//                {
//                    b.Property<int>("id")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("DisciplineId");

//                    b.Property<int>("PlayId");

//                    b.Property<int>("ToiletId");

//                    b.HasKey("id");

//                    b.ToTable("Cares");
//                });

//            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Unicorn", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int?>("Careid");

//                    b.Property<string>("FirstName");

//                    b.Property<string>("LastName");

//                    b.Property<string>("ThirdName");

//                    b.HasKey("Id");

//                    b.HasIndex("Careid");

//                    b.ToTable("Unicorns");
//                });

//            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Unicorn", b =>
//                {
//                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.Care", "Care")
//                        .WithMany()
//                        .HasForeignKey("Careid");
//                });
//#pragma warning restore 612, 618
//        }
//    }
}
